In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
dataset = pd.read_csv('Data.csv', sep=';')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(dataset.head())

   country   age   salary purchased
0   france  44.0  72000.0        no
1    spain  27.0  48000.0       yes
2  germany  30.0  54000.0        no
3    spain  38.0  61000.0        no
4  germany  40.0      NaN      yes 


In [6]:
print(x)

[['france' 44.0 72000.0]
 ['spain' 27.0 48000.0]
 ['germany' 30.0 54000.0]
 ['spain' 38.0 61000.0]
 ['germany' 40.0 nan]
 ['france' 35.0 58000.0]
 ['spain' nan 52000.0]
 ['france' 48.0 79000.0]
 ['germany' 50.0 83000.0]
 ['france' 37.0 67000.0]
 ['indonesia' 20.0 50000.0]
 ['france' 22.0 45000.0]
 ['indonesia' 45.0 21400.0]
 ['indonesia' 29.0 40000.0]]


In [7]:
print(y)

['no' 'yes' 'no' 'no' 'yes ' 'yes' 'no' 'yes' 'no' 'yes' 'no' 'yes' 'no'
 'no']


In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [9]:
print(x)

[['france' 44.0 72000.0]
 ['spain' 27.0 48000.0]
 ['germany' 30.0 54000.0]
 ['spain' 38.0 61000.0]
 ['germany' 40.0 56184.61538461538]
 ['france' 35.0 58000.0]
 ['spain' 35.76923076923077 52000.0]
 ['france' 48.0 79000.0]
 ['germany' 50.0 83000.0]
 ['france' 37.0 67000.0]
 ['indonesia' 20.0 50000.0]
 ['france' 22.0 45000.0]
 ['indonesia' 45.0 21400.0]
 ['indonesia' 29.0 40000.0]]


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [12]:
print(x)

[[1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 40.0 56184.61538461538]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 35.76923076923077 52000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 0.0 20.0 50000.0]
 [1.0 0.0 0.0 0.0 22.0 45000.0]
 [0.0 0.0 1.0 0.0 45.0 21400.0]
 [0.0 0.0 1.0 0.0 29.0 40000.0]]


In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [14]:
print(y)

[0 1 0 0 2 1 0 1 0 1 0 1 0 0]


In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [18]:
print(x_train)

[[0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 0.0 20.0 50000.0]
 [0.0 1.0 0.0 0.0 40.0 56184.61538461538]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 45.0 21400.0]
 [1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 0.0 29.0 40000.0]
 [1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 22.0 45000.0]
 [1.0 0.0 0.0 0.0 35.0 58000.0]]


In [19]:
print(x_test)

[[0.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 1.0 35.76923076923077 52000.0]]


In [20]:
print(y_train)

[0 0 2 1 0 0 0 1 0 1 1]


In [21]:
print(y_test)

[0 1 0]


In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])

In [23]:
print(x_train)

[[0.0 1.0 0.0 -0.316227766016838 -0.4791502965599001
  -0.003363442280190084]
 [0.0 0.0 1.0 -0.316227766016838 -1.5547938194494721 -0.25650672968398974]
 [0.0 1.0 0.0 -0.316227766016838 0.5964932263296719 0.13489173776342347]
 [0.0 0.0 0.0 3.16227766016838 -0.8018433534267717 -0.38307837338588957]
 [0.0 0.0 1.0 -0.316227766016838 1.1343149877744578 -2.066481234621157]
 [1.0 0.0 0.0 -0.316227766016838 1.0267506354855007 1.1357813510369084]
 [0.0 0.0 1.0 -0.316227766016838 -0.5867146488488574 -0.8893649481934889]
 [1.0 0.0 0.0 -0.316227766016838 0.2738001694628003 0.8193522417821588]
 [0.0 1.0 0.0 -0.316227766016838 1.6721367492192438 1.8319253913973574]
 [1.0 0.0 0.0 -0.316227766016838 -1.3396651148715577 -0.5729358389387393]
 [1.0 0.0 0.0 -0.316227766016838 0.058671464884885886 0.24977984512360957]]


In [24]:
print(x_test)

[[0.0 0.0 0.0 0.7071067811865476 -0.4869407000953254 -0.2672612419124244]
 [1.0 0.0 0.0 -1.414213562373095 1.3933253695796926 1.3363062095621219]
 [0.0 0.0 0.0 0.7071067811865476 -0.9063846694843684 -1.0690449676496976]]
